---
language: ruby
bundler_args: --without system_tests --full-index
before_install: rm Gemfile.lock || true
script: ["bundle exec rake test"]
rvm:
  - 2.1
  - 2.2
  - 2.3.0
env:
  - PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="~> 4.9.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 5.4.0" STRICT_VARIABLES=yes
deploy:
  provider: puppetforge
  user: kschu91
  password:
    secure: cwYlCnNUj/Df6JC8wjvu2DWF9K7MkLPYRHp8Cf21bEmj6gotIjPK9EFLoSmBelSanb1XWRd5PTvCcVPaD8sHpJ9n9D9tLzfFOwzgwjuveq54aIEqY+OMKf6s1IdFOSfx5iSXS8cX6DJ3fH7N/J7kNavghmPHA0ucHSj415j6kKS8K0ozoJAqbS0C2/niOxeg7I/RMix9Z61UpA1rNjLMVcl/Q6dlFUALVDVM8X8n2WL3lVH0iZIEeRJMSkgCI00iM8e8rVxccmaK5wkes/xyIH0o2UiFIIvlEOZIdOMtVoLNEdnov1rJ0v2Nyqc+HjFLGIQ61boPBG61ixwSEse8vVb6Z18NcjEeeQ8gVl4yUywgXZQdJ94TPUScfxJKN+kIJmOKuj+Q/Jlq+Eji/SmIr94xoNcZmD/v1ce709YPfYM46u3iKHDik5oINzJSj9myWCY9XE5r6Nkf5aRmWOAcgs0lbr0S/6oj/x1wCcvm3kO7ePpNHNcZSFS/qAuFer5c5F/dpoJ/ktecJ4GhCj06FY1iut4KzywerZC1j1Eej8G4VUMnbW4yk0E4fy3kFFUTCKBs3edrFlnfLu/uK0bwE4y5ua4feMKjQ6+y53LvsJ6+RlvaIhT2MehnNTCjVQgUgowq/x7yx+0356cM+qkRCdbLk+av/ikei3C1Fkj1/4k=
  on:
    tags: true
    # Only publish if our main Ruby target builds
    rvm: 2.1
    condition: $PUPPET_GEM_VERSION = "~> 5.4.0"