language: ruby
bundler_args: "--without system_tests --full-index"
before_install: rm Gemfile.lock || true
script:
- bundle exec rake test
rvm:
- 2.4
env:
- PUPPET_GEM_VERSION="~> 4.9.0" STRICT_VARIABLES=yes
- PUPPET_GEM_VERSION="~> 5.3.0" STRICT_VARIABLES=yes
- PUPPET_GEM_VERSION="~> 5.4.0" STRICT_VARIABLES=yes
- PUPPET_GEM_VERSION="~> 6.0.0" STRICT_VARIABLES=yes
matrix:
  exclude:
    # puppet 6.x requires ruby 2.3 or higher
    - rvm: 2.2
      env: PUPPET_GEM_VERSION="~> 6.0.0" STRICT_VARIABLES=yes
deploy:
  provider: puppetforge
  user: kschu91
  password:
    secure: PqBO19a1fuDeBfaV8j13QneTKWi3PXUumMEv0XMrm70Pvh2zekDSChEj5uj+jr5LEhisZq93HeAeVUxgbyFXF24sgkxsdwLn/eYVFeAN0ienJ3HBf9iIo7IfaeieT7Q7rzD0bWEbBdRzS8/EIxpTs8Qub81c+R8kEcOB/GaVDS3UDAWDwAlGoSMt95hsWJEXEEgAsfQ/AGS7USYIzkWJrX35sJj48OLboWhIMmZYbM6+4E81f5P5hhwITxy3Ue4uRXRtYl9oIc6i+HKsJazPlg8/Homga62C7RshDq9EpDPo63MylTVik+e+EyPvoXBY1O/Fu4oj43o4qty3pfpAAOSWti4FsgVn7edKATPqovImEk814gs9H25UUJmsYIi+fRxrrTUjw3Nj2b6LoUEEh20JmZq6O+bjoE8UO4hNBkkJoK4M/DtLmBMTtaaoRtG2UO2+/Fh7HP6pH8cZp8fLLJpC27iE8ESo5My4SuB/G6pskaPRLQyE3Oyym0B1/tVOxmt33+iiQyoZosXLAJNLeMS5zP6V74TEW1MjTD31iyHxc+F00Y8JbotT9y+Fc8tvBYzW10aMjlVA8Hm+ANbkVKKSgji4eOA1NY/+pBdP4i49gexzXo2V4niW8375T9WvMu42bzBpPsd9p1G4c674KJc3d88R83AyTAFvpi494Vs=
  on:
    tags: true
    rvm: 2.4
    condition: $PUPPET_GEM_VERSION = "~> 5.4.0"
