---
language: ruby
bundler_args: --without system_tests --full-index
before_install: rm Gemfile.lock || true
script: ["bundle exec rake test"]
rvm:
  - 2.1
  - 2.2
  - 2.3.0
env:
  - PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="~> 4.9.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 5.4.0" STRICT_VARIABLES=yes
deploy:
  provider: puppetforge
  user: kschu91
  password:
    secure: Mm1DPqsx9MdxRtzMJ+HKRr9rVRATckrZnUHTqVshWxIzjsqZHvi44y9TAtowT5qT2P6RjXgXrT+2XcT+S0JPN4sgI3No0TFzozifrG72XgMWv7zB3h1FEaTQmlQU3QQ8OTdBoxoyQGwFq16qDKRdi2duvfQHJveDQ+kBN/DsBhOxaJcV3PowdWxYZ+3OklnYbrfQlM8yWB65G63Em8Ez6KanaBCUzLZeQrpdtEDBRS+JYkjOvbifU3LaKly74qjj9FvYpqkBg9vcbxX3sO6+5AssxIm8z1WNnv52uaEPx6KDP3yBQxknarinajQBZgi3Y+my2Q1B+lJGwigM8rIUT6OjuhEPfGQL6UKaqPRFLt3iVpg8P0PS1WwCzgYEiQSN39eRpOuWIBKJvFqK0+9R9heJ46I9O1J17ePUVKXUU5rYktW3dnUtB+/rf8SEeYvN3395wI61x4J8JEQCpX60QLw0wI4dUq5TTcJRycvaSwmOCcNYa3IO19/j10klOhUXj0avO11hhw+B3GMp9snpOup57Fh1AomNSwMxe46DGlbMu32G7iNiABo0TbrEA9WRCQDgDdMY2IxzyKQBS0JuND9uVo6/DsOhTeJZ1sOjvbUTxNbdp8fruE9ne8ROZPnwkFbT7cj4UFiX9k2tD9vNOHWjRvC5hNPCZ/79HuMNkPg=
  on:
    tags: true
    # Only publish if our main Ruby target builds
    rvm: 2.1
    condition: $PUPPET_GEM_VERSION = "~> 5.4.0"