language: ruby
bundler_args: "--without system_tests --full-index"
before_install: rm Gemfile.lock || true
script:
- bundle exec rake test
rvm:
- 2.2
- 2.4
env:
- PUPPET_GEM_VERSION="~> 2.7.0" STRICT_VARIABLES=yes
- PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=no
- PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
- PUPPET_GEM_VERSION="~> 4.9.0" STRICT_VARIABLES=yes
- PUPPET_GEM_VERSION="~> 5.3.0" STRICT_VARIABLES=yes
- PUPPET_GEM_VERSION="~> 5.4.0" STRICT_VARIABLES=yes
deploy:
  provider: puppetforge
  user: kschu91
  password:
    secure: nDcgwuPq6gC/2jqoiysWj0CbPfykUoHBefpiTaWZ2PXiXjEEgJwSSRb6e+GsTeDrSA4iz+1JH7zQNEXLqUBVsfnV96fVblVB+xTgzRIpB+q2jf4SEvESzDdBRgmoGcO/kjs5ZEv13E+RKKf7Ukeo8DzTtHhrGl+8P7G5s7AvwqvQtFlEPpKiSzCMROpmRSPKjg+i47Rq+h0cC0TUK6HCimiGR4D0EupRBeb5qPtzuC9+Nf7OMiMqogCCDQYxtppNLVDQLwzbf6DZ/a39UQPVjGMsSEZXHgDrLRBMK7qVT9qeRpHs8BbDCyqg7Eeb96ZmmtZsYVaihu02XDpV14wokyTh546KmnnPbKTiJESokovUHZic+Q0/3W75+D2AdxsbjokB3Pv6qRMqkMxyfNjgFLInklFu+CC7cXAsp/8qUQYu1rFTcdJ2LeCwTxLQpCZz70aHcXStGnheqy8n/OJxeKkIdkodebqyjw45N2q63sqap7/bCDy/vO4sxNPpRMDnrMOsNC68/JYYaTYem/AMfdqXNt4tZRJs4kJxlc2rBk7j3UTYhgE84d1+K/FS4IgNPqYTSjnxxRAsp0TU3ZLnS94Uszo+oJt1TEw+RkHfvpis2QRKSmuN6Nwlo/wUJphGpYlaWhV0N7tKpo/19bdGgXtqdJIXhH6xkaGTEQaL+Qk=
  on:
    tags: true
    rvm: 2.4
    condition: $PUPPET_GEM_VERSION = "~> 5.4.0"
