language: ruby
bundler_args: "--without system_tests --full-index"
before_install: rm Gemfile.lock || true
script:
- bundle exec rake test
rvm:
- 2.1
- 2.2
- 2.3.0
env:
- PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
- PUPPET_GEM_VERSION="~> 4.9.0" STRICT_VARIABLES=yes
- PUPPET_GEM_VERSION="~> 5.4.0" STRICT_VARIABLES=yes
deploy:
  provider: puppetforge
  user: kschu91
  password:
    secure: okJ9mKikwhoxUhrSX4Nh4MnWQhB2zQpfeIzfbsZZUYNKRR8qVpn5ZkdWGlDGGDwYg8TSwUP7sY4mrS38/etYp7zcXVHmtgf/pe1HA7xyT1w3Auk6F/eRBbtt1rCWr7CgdCf9WAHVVzAZDYzaakcjPIKkzWFu4y9mPLV2Z5h3sXAzlRvDnsPQVvJuGA8y3t6h7BJXRDbxQjXc9s3XdPNmS3xYXjRnMOlpWYZdyJTkLuXDCpoqR3OX1PNZLEfePzjVvrqJHB/v/FC7m8GeWHFqFWinLY1v5Zh5JGwQ9Uz6ycIvvNFohqbQteTxMDFzRUhyFBGyhriJafJwM4A94gh7XxCIy46Xy6gB5+79wXfK1vlhnWjgFDqoGUXwZThz+/bY4QA1fRKPaKanIOY2BhuJtX+hlRbq8yYzP79Z5p1fXhodwpdLvAHZ4GrMq1c5jbx8LqBq4zD3OMXasWOwz8qXD2I3kCBkG0pL1hM+0s72r0oTE4RAGwj/XKmNYewmc3pYZSAWvD27IkNTccDvzG/s2osZyua+EePBpYxDGmnfBaJj5QR/XawZTUuE5CqhDesVIPJDM1+FwTKpii1Pg1BK2UBO47bIhQAkqeYB+VuUDGtT9sRQijY8LzKnKL7XRfDV/Yu7wS4kHCT/sGN7k58QR/Jt6KxP0Pp9zbSOi2uhDSs=
  on:
    tags: true
    rvm: 2.1
    condition: $PUPPET_GEM_VERSION = "~> 5.4.0"
