language: ruby
bundler_args: "--without system_tests --full-index"
before_install: rm Gemfile.lock || true
script:
- bundle exec rake test
rvm:
- 2.1
- 2.2
- 2.3.0
env:
- PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
- PUPPET_GEM_VERSION="~> 4.9.0" STRICT_VARIABLES=yes
- PUPPET_GEM_VERSION="~> 5.4.0" STRICT_VARIABLES=yes
deploy:
  provider: puppetforge
  user: kschu91
  password:
    secure: eDBE3d+0VmmtGO+wFR088RYOrESOuRdA5qOjY8qdrN6dwCQxFXyaNIQ8UUr37rhlD4pm7c390N+Xour7jRVjbLcfF8VA5p3tRajYI1Wx4dB7ehmNNCBfdkXHc5nRz8jdCXBp5YjNuILRQXXaf4AjQfAscsuW3WFR4dSMpxsWubp2uBgyOGruOE3UJC3hiDbme2dYkT1cH/8etpZ4CTfyUasGe/8shRdvxbEFITesvTHrINeFsSIEslMQoKuYBx8mFXXDf/GFCpLlUip/H3sSwlX0APGV5JXILK3q8Awtht3peM0wlhiJxEfdCSMO05Lcs6SHk8jZXexXMrUE7A21otHwDJnwYMC1iVhCsZ4wxgKBStV5IHbeAxQGGORAwJROt+y8ElXlYHuWY3OwTF05VpaCpo9NtyO+9JRkBQZXqBgMkM4IV1CvZkbelsDXYBWXrq67i2ho6Ng+zVHB6KkV1YJCa2iJ/o327ueuPic/tLbZf+TmFGUiNfz1JGpK7LGgf3ZFCWUOLX8E6awm/gbRM1BVdcdHJfhOGh/cx6B5qswCvrUiizAhzR0UTpo9CojO2l6jbKPEhOcGHl6oOkMDV+GBQ9S9VfkwDH3oC8TwYiw1MVRI2Cc6VslZZBKiYNRT7YtH/Lw4SlADvBizqe0nA8Bskv6qSmRgbzQVJlaujGk=
  on:
    tags: true
    rvm: 2.1
    condition: $PUPPET_GEM_VERSION = "~> 5.4.0"
